### ISSUE TITLE
ATOM feed broken

### ISSUE THREAD

**Issue by joschi** [jcgregorio/blog#2]
Since migrating this blog to Hugo, the ATOM feed which was previously available at https://bitworking.org/news/feed/index.atom is broken.

**Comment by jcgregorio** [comment]
Should be fixed by:

  https://github.com/jcgregorio/blog/commit/bcd5cce99991573a1eeb1bfcda083e5074e1b7fd

Thanks!

**Comment by joschi** [comment]
It's working, thanks!
